site_name: Kessel
docs_dir: docsrc
site_dir: docs
site_description: 'Kessel parser combinators for JavaScript'
site_author: 'Thomas J. Otterson'
copyright: 'Copyright &copy; 2020 Thomas J. Otterson'

repo_url: https://github.com/Barandis/kessel
edit_uri: ''

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - footnotes

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.tabs

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - "User's Guide":
    - Introduction: guide/ch-00.md
    - '1. Parsers Parsers Parsers': guide/ch-01.md
    - '2. Making Parsers Go': guide/ch-02.md
    - '3. Parsers, How Do They Work?': guide/ch-03.md
    - '4. Combining Parsers': guide/ch-04.md
  - Tutorial:
    - Introduction: tutorial/ch-00.md
  - 'API Reference':
    - Summary: api.md
    - Parsers:
      - all: parsers/all.md
      - alpha: parsers/alpha.md
      - alphaU: parsers/alphau.md
      - alt: parsers/alt.md
      - always: parsers/always.md
      - any: parsers/any.md
      - anyOf: parsers/anyof.md
      - anyString: parsers/anystring.md
      - apply: parsers/apply.md
      - applyB: parsers/applyb.md
      - assoc1L: parsers/assoc1l.md
      - assoc1R: parsers/assoc1r.md
      - assocL: parsers/assocl.md
      - assocR: parsers/assocr.md
      - attempt: parsers/attempt.md
      - between: parsers/between.md
      - betweenB: parsers/betweenb.md
      - block: parsers/block.md
      - blockB: parsers/blockb.md
      - chain: parsers/chain.md
      - chainB: parsers/chainb.md
      - char: parsers/char.md
      - charI: parsers/chari.md
      - compact: parsers/compact.md
      - def: parsers/def.md
      - digit: parsers/digit.md
      - empty: parsers/empty.md
      - end: parsers/end.md
      - end1: parsers/end1.md
      - eof: parsers/eof.md
      - failFatally: parsers/failfatally.md
      - failNormally: parsers/failnormally.md
      - fifth: parsers/fifth.md
      - first: parsers/first.md
      - fourth: parsers/fourth.md
      - hex: parsers/hex.md
      - join: parsers/join.md
      - left: parsers/left.md
      - leftB: parsers/leftb.md
      - letter: parsers/letter.md
      - letterU: parsers/letteru.md
      - lower: parsers/lower.md
      - lowerU: parsers/loweru.md
      - many: parsers/many.md
      - many1: parsers/many1.md
      - manyTillB: parsers/manytillb.md
      - map: parsers/map.md
      - newline: parsers/newline.md
      - newlineU: parsers/newlineu.md
      - noneOf: parsers/noneof.md
      - not: parsers/not.md
      - nth: parsers/nth.md
      - octal: parsers/octal.md
      - opt: parsers/opt.md
      - peek: parsers/peek.md
      - pipe: parsers/pipe.md
      - pipeB: parsers/pipeb.md
      - range: parsers/range.md
      - regex: parsers/regex.md
      - repeat: parsers/repeat.md
      - repeatB: parsers/repeatb.md
      - right: parsers/right.md
      - rightB: parsers/rightb.md
      - satisfy: parsers/satisfy.md
      - satisfyM: parsers/satisfym.md
      - second: parsers/second.md
      - sep: parsers/sep.md
      - sep1: parsers/sep1.md
      - seq: parsers/seq.md
      - seqB: parsers/seqb.md
      - skip: parsers/skip.md
      - space: parsers/space.md
      - spaces: parsers/spaces.md
      - spaces1: parsers/spaces1.md
      - spaces1U: parsers/spaces1u.md
      - spacesU: parsers/spacesu.md
      - spaceU: parsers/spaceu.md
      - string: parsers/string.md
      - stringI: parsers/stringi.md
      - third: parsers/third.md
      - until: parsers/until.md
      - upper: parsers/upper.md
      - upperU: parsers/upperu.md
      - value: parsers/value.md
    - Tools:
      - compound: tools/compound.md
      - expected: tools/expected.md
      - failReply: tools/failreply.md
      - failure: tools/failure.md
      - fatalReply: tools/fatalreply.md
      - formatErrors: tools/formaterrors.md
      - generic: tools/generic.md
      - getPosition: tools/getposition.md
      - merge: tools/merge.md
      - nested: tools/nested.md
      - okReply: tools/okreply.md
      - other: tools/other.md
      - parse: tools/parse.md
      - parser: tools/parser.md
      - run: tools/run.md
      - status: tools/status.md
      - succeeded: tools/succeeded.md
      - success: tools/success.md
      - unexpected: tools/unexpected.md
    - Types:
      - CompoundError: types/compounderror.md
      - Context: types/context.md
      - ErrorList: types/errorlist.md
      - ErrorType: types/errortype.md
      - Formatter: types/formatter.md
      - Input: types/input.md
      - LocalError: types/localerror.md
      - NestedError: types/nestederror.md
      - Parser: types/parser.md
      - Reply: types/reply.md
      - Result: types/result.md
      - Status: types/status.md
